run_operator() {

    if [ $# -ne 2 ]; then
        echo "Usage:"
        echo "  ./run.sh add_two_numbers <num1> <num2>"
        return 1
    fi

    NUM1="$1"
    NUM2="$2"

    HOST="$OP_DIR/build/host_add_two_numbers"
    XCLBIN="$OP_DIR/build/add_two_numbers.hw.xclbin"

    if [ ! -x "$HOST" ]; then
        echo "[ERROR] Executable not found:"
        echo "        $HOST"
        return 1
    fi

    if [ ! -f "$XCLBIN" ]; then
        echo "[ERROR] xclbin not found:"
        echo "        $XCLBIN"
        return 1
    fi

    echo "[RUN]"
    echo "$HOST $XCLBIN $NUM1 $NUM2"

    "$HOST" "$XCLBIN" "$NUM1" "$NUM2"
}
